version: '3'
services:

  typexs_base_test_mongo:
    image: mongo:4
    ports:
    - 127.0.0.1:27017:27017
    volumes:
    - ./local/mongodb:/data/db


  typexs_base_test_redis:
    image: redis:5
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./local/redis/db:/data
